name: Build & Push Docker

on:
  push:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/build-push-action@v5
        with:
          context: ./BE
          push: true
          tags: minh123333/colorandtruth:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Trigger Railway Redeploy
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.RAILWAY_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"query": "mutation { serviceInstanceRedeploy(environmentId: \"92b206ac-97bc-4e76-ac87-ad3dfefb9e6a\", serviceId: \"5e2c6acf-2d94-41ac-99fd-5f003003b9e1\") }"}' \
            https://backboard.railway.app/graphql/v2